### ISSUE TITLE
Homepage services.yaml setup question.

### ISSUE THREAD

**Issue by Healzangels** [10mfox/Gethomepage-Tautulli-Custom-Api#1]
Greetings! Thanks for sharing such a cool sounding Homepage integration. 

As this was recently added as a template within the Unraid Community Apps figured I'd give it a whirl.
I've completed the setup so far following the Quick Start. All seemed well here/understood.

The setup question I'm wondering/hoping for possible direction on is what the config for the Customapi integration with homepage would look like.
Unfortunately something I'm not overly familiar with so apologies for what is probably a pretty basic question! 

Following another customapi integration I got as far as: 

``` 
    - TautulliCustom:
        icon: placeholder
        href: placeholder 
        description: Recently Added
        server: my-docker
        container: Homepage-Tautulli-Integration             
        widget:
          type: customapi
          url: http://10.0.1.98:3008
          method: GET
```
Was hoping if possible for a few examples of what the configuration on the homepage services.yaml may look like.
My goal would be to be able to display what was recently added in my Movies, TV Shows, and Anime libraries within homepage.

Cheers and thanks again!
